# Full-stack services for Exoplanet Detector (backend API, frontend UI, and monitoring)
services:
  exoplanet-api:
    # Python FastAPI backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exoplanet-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - API_VERSION=1.0.0
      - LOG_LEVEL=INFO
      - ENABLE_MODEL_CACHING=true
      - CACHE_TTL=3600
      - MODEL_FULL_PATH=/app/models/exoplanet_model.keras
      - PYTHONPATH=/app/src
    volumes:
      - ./models:/app/models
    depends_on:
      - redis
    networks:
      - exoplanet-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    # Caching backend for Celery/tasks (optional)
    image: redis:7-alpine
    container_name: exoplanet-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - exoplanet-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  prometheus:
    # Metrics scraper (optional)
    image: prom/prometheus:latest
    container_name: exoplanet-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    networks:
      - exoplanet-network
    depends_on:
      - exoplanet-api

  grafana:
    # Metrics dashboards (optional)
    image: grafana/grafana:latest
    container_name: exoplanet-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
    networks:
      - exoplanet-network

  frontend:
    # React + Vite build served by Nginx
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: exoplanet-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - exoplanet-api
    networks:
      - exoplanet-network

  worker:
    # Celery worker calling the API (optional)
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exoplanet-worker
    restart: unless-stopped
    command: celery -A src.backend.tasks worker --loglevel=info --concurrency=2
    environment:
      - LOG_LEVEL=INFO
      - REDIS_URL=redis://redis:6379/0
      - API_BASE_URL=http://exoplanet-api:8000
      - PYTHONPATH=/app/src
    volumes:
      - ./models:/app/models
    depends_on:
      - redis
      - exoplanet-api
    networks:
      - exoplanet-network

volumes:
  redis-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  exoplanet-network:
    driver: bridge
